local musicSets = {
	
	mpheist_track1 = {
		name = "Heists Track 1",
		gameOrigin = "GTA: Online",
		composer = "Tangerine Dream, Woody Jackson",
		category = "Original Heists",
		path = "gta5/mpheist/mpheist_track_1",
		stems = {
			"MPHEIST_TRACK1_1.mp3",
			"MPHEIST_TRACK1_2.mp3",
			"MPHEIST_TRACK1_3.mp3",
			"MPHEIST_TRACK1_4.mp3",
			"MPHEIST_TRACK1_5.mp3",
			"MPHEIST_TRACK1_6.mp3",
			"MPHEIST_TRACK1_7.mp3",
			"MPHEIST_TRACK1_8.mp3",
		},
	},

	mpheist_track2 = {
		name = "Heists Track 2",
		gameOrigin = "GTA: Online",
		composer = "Tangerine Dream, Woody Jackson",
		category = "Original Heists",
		path = "gta5/mpheist/mpheist_track_2",
		stems = {
			"MPHEIST_TRACK2_1.mp3",
			"MPHEIST_TRACK2_2.mp3",
			"MPHEIST_TRACK2_3.mp3",
			"MPHEIST_TRACK2_4.mp3",
			"MPHEIST_TRACK2_5.mp3",
			"MPHEIST_TRACK2_6.mp3",
			"MPHEIST_TRACK2_7.mp3",
			"MPHEIST_TRACK2_8.mp3",
		},
	},

	mpheist_track3 = {
		name = "Heists Track 3",
		gameOrigin = "GTA: Online",
		composer = "Tangerine Dream, Woody Jackson",
		category = "Original Heists",
		path = "gta5/mpheist/mpheist_track_3",
		stems = {
			"MPHEIST_TRACK3_1.mp3",
			"MPHEIST_TRACK3_2.mp3",
			"MPHEIST_TRACK3_3.mp3",
			"MPHEIST_TRACK3_4.mp3",
			"MPHEIST_TRACK3_5.mp3",
			"MPHEIST_TRACK3_6.mp3",
			"MPHEIST_TRACK3_7.mp3",
			"MPHEIST_TRACK3_8.mp3",
		},
	},

	mpheist_track4 = {
		name = "Heists Track 4",
		gameOrigin = "GTA: Online",
		composer = "Tangerine Dream, Woody Jackson",
		category = "Original Heists",
		path = "gta5/mpheist/mpheist_track_4",
		stems = {
			"MPHEIST_TRACK4_1.mp3",
			"MPHEIST_TRACK4_2.mp3",
			"MPHEIST_TRACK4_3.mp3",
			"MPHEIST_TRACK4_4.mp3",
			"MPHEIST_TRACK4_5.mp3",
			"MPHEIST_TRACK4_6.mp3",
			"MPHEIST_TRACK4_7.mp3",
			"MPHEIST_TRACK4_8.mp3",
		},
	},

	mpheist_track5 = {
		name = "Heists Track 5",
		gameOrigin = "GTA: Online",
		composer = "Tangerine Dream, Woody Jackson",
		category = "Original Heists",
		path = "gta5/mpheist/mpheist_track_5",
		stems = {
			"MPHEIST_TRACK5_1.mp3",
			"MPHEIST_TRACK5_2.mp3",
			"MPHEIST_TRACK5_3.mp3",
			"MPHEIST_TRACK5_4.mp3",
			"MPHEIST_TRACK5_5.mp3",
			"MPHEIST_TRACK5_6.mp3",
			"MPHEIST_TRACK5_7.mp3",
			"MPHEIST_TRACK5_8.mp3",
		},
	},

	mpheist_track6 = {
		name = "Heists Track 6",
		gameOrigin = "GTA: Online",
		composer = "Tangerine Dream, Woody Jackson",
		category = "Original Heists",
		path = "gta5/mpheist/mpheist_track_6",
		stems = {
			"MPHEIST_TRACK6_1.mp3",
			"MPHEIST_TRACK6_2.mp3",
			"MPHEIST_TRACK6_3.mp3",
			"MPHEIST_TRACK6_4.mp3",
			"MPHEIST_TRACK6_5.mp3",
			"MPHEIST_TRACK6_6.mp3",
			"MPHEIST_TRACK6_7.mp3",
			"MPHEIST_TRACK6_8.mp3",
		},
	},

	mpheist_track7 = {
		name = "Heists Track 7",
		gameOrigin = "GTA: Online",
		composer = "Tangerine Dream, Woody Jackson",
		category = "Original Heists",
		path = "gta5/mpheist/mpheist_track_7",
		stems = {
			"MPHEIST_TRACK7_1.mp3",
			"MPHEIST_TRACK7_2.mp3",
			"MPHEIST_TRACK7_3.mp3",
			"MPHEIST_TRACK7_4.mp3",
			"MPHEIST_TRACK7_5.mp3",
			"MPHEIST_TRACK7_6.mp3",
			"MPHEIST_TRACK7_7.mp3",
			"MPHEIST_TRACK7_8.mp3",
		},
	},

	mpheist_track8 = {
		name = "Heists Track 8",
		gameOrigin = "GTA: Online",
		composer = "Tangerine Dream, Woody Jackson",
		category = "Original Heists",
		path = "gta5/mpheist/mpheist_track_8",
		stems = {
			"MPHEIST_TRACK8_1.mp3",
			"MPHEIST_TRACK8_2.mp3",
			"MPHEIST_TRACK8_3.mp3",
			"MPHEIST_TRACK8_4.mp3",
			"MPHEIST_TRACK8_5.mp3",
			"MPHEIST_TRACK8_6.mp3",
			"MPHEIST_TRACK8_7.mp3",
			"MPHEIST_TRACK8_8.mp3",
		},
	},
}

return musicSets